services:
  ros-flir:
    build:
      context: ../..
      dockerfile: docker/nano/Dockerfile.flir
    container_name: ros-flir
    network_mode: host
    ipc: host
    devices:
      - /dev/video0:/dev/video0
      - /dev/video2:/dev/video2
    restart: unless-stopped
