# this can be optimized
FROM ros:jazzy-ros-core

# set runtime environment variables
ENV ROS_DOMAIN_ID=69

# setup working directory
WORKDIR /app

# install system dependencies
#RUN apt-get update && apt-get install -y \
    # libboost-all-dev \
    # libyaml-cpp-dev \
    # build-essential \
    # cmake \
    # ros-jazzy-foxglove-bridge \
    # ros-jazzy-rosbag2 \
    # python3-paho-mqtt \
    # python3-zstandard \
    # python3-colcon-common-extensions \
    # python3-rosdep

# copy multisense driver code
COPY src/multisense_stereo_camera src/multisense_stereo_camera

# copy launch script
COPY launch/multisense_launch.py launch.py

# install ros invoked dependencies and build
# docker RUN commands will initialize new shell so source need to be run.
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    python3-colcon-common-extensions \
    python3-rosdep && \
    . /opt/ros/jazzy/setup.sh && \
    rosdep init &&  \
    rosdep update && \
    rosdep install --from-paths src -y --ignore-src && \
    colcon build --symlink-install

# launch ros package
CMD ["bash", "-c", "source install/setup.bash && ros2 launch launch.py"]
