# uses a base image that has all ros2 and sensor drivers installed
FROM ros-base-with-rosdep

WORKDIR /app

# launch ros package
CMD ["bash", "-c", "source install/setup.bash && ros2 launch launch/lidar_launch.py"]
