# this can be optimized
FROM ros:jazzy-ros-core

# setup working directory
WORKDIR /app

# copy all drivers' code and launch script
COPY src/HesaiLidar_ROS_2.0 src/HesaiLidar_ROS_2.0
COPY src/v4l2_camera src/v4l2_camera
COPY src/multisense_stereo_camera src/multisense_stereo_camera
COPY launch/nano_all_drivers_launch.py launch.py

# install system dependencies
RUN apt-get update && apt-get install -y \
    libboost-all-dev \
    libyaml-cpp-dev \
    build-essential \
    cmake \
    ros-jazzy-foxglove-bridge \
    ros-jazzy-rosbag2 \
    python3-paho-mqtt \
    python3-zstandard \
    python3-colcon-common-extensions \
    python3-rosdep

# setup environment variable to enable ROS discovery data between computers
ENV ROS_DOMAIN_ID=69

# install ros invoked dependencies and build
# docker RUN commands will initialize new shell so source need to be run.
RUN . /opt/ros/jazzy/setup.sh && \
    rosdep init &&  \
    rosdep update && \
    rosdep install --from-paths src -y --ignore-src && \
    colcon build --symlink-install

# launch ros package
CMD ["bash", "-c", "source install/setup.bash && ros2 launch launch.py"]

