# this can be optimized
FROM ros:jazzy-ros-core

# setup working directory
WORKDIR /app

# copy multisense driver code
COPY src/multisense_stereo_camera src/multisense_stereo_camera

# copy launch script
COPY launch/multisense_launch.py launch.py
COPY cyclonedds.xml cyclonedds.xml

# install ros invoked dependencies and build
# docker RUN commands will initialize new shell so source need to be run.
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    python3-colcon-common-extensions \
    ros-jazzy-rmw-cyclonedds-cpp \
    python3-rosdep && \
    . /opt/ros/jazzy/setup.sh && \
    rosdep init &&  \
    rosdep update && \
    rosdep install --from-paths src -y --ignore-src && \
    colcon build --symlink-install

# set dds and ros domain
ENV ROS_DOMAIN_ID=69 \
    CYCLONEDDS_URI=file:///app/cyclonedds.xml \
    RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

# launch ros package
CMD ["bash", "-c", "source install/setup.bash && ros2 launch launch.py"]
