# runs all nodes found in src, without starting recording

# this can be optimized
FROM ros-base-with-rosdep

# setup working directory
WORKDIR /app

# launch ros package
CMD ["bash", "-c", "source install/setup.bash && ros2 launch launch/all_sensor_drivers_launch.py"]
