services:
  kuksa-databroker:
    image: ghcr.io/eclipse-kuksa/kuksa-databroker:latest
    container_name: databroker
    networks:
      - kuksa
    ports:
      - 55555:55555
    volumes:
      - ./setup/vss:/vss
    command: "--insecure --vss /vss/vss.json"

  kuksa-provider:
    image: ghcr.io/eclipse-kuksa/kuksa-can-provider/can-provider:latest
    container_name: can-provider
    environment:
      - KUKSA_ADDRESS=kuksa-databroker
    networks:
      - kuksa
    volumes:
      - ./setup:/setup
    command: "--dbcfile /setup/provider/toyota_rav4_hybrid_2017.dbc --dumpfile /setup/provider/logs/candump.log --mapping /setup/vss/vss.json"

# This is only for the kuksa provider and databroker
networks:
  kuksa:
    name: kuksa-docker
    external: true
