services:
  kuksa-databroker:
    image: ghcr.io/eclipse-kuksa/kuksa-databroker:latest
    networks:
      - kuksa
    ports:
      - 55555:55555
    command: "--insecure"

# This is only for the kuksa provider and databroker
networks:
  kuksa:
    name: kuksa-docker
    external: true
