version: "3.9"

services:
  ros-nano-all-drivers:
    build:
      context: ..
      dockerfile: docker/Dockerfile.nano_all_drivers
    image: ros-nano-all-drivers:latest
    container_name: ros-nano-all-drivers
    network_mode: host
    devices:
      - /dev/video0:/dev/video0
      - /dev/video2:/dev/video2
    volumes:
      - /mnt/Burak2/ros-device-control/bags:/app/bags
    restart: unless-stopped
