FROM ros:jazzy-ros-core

# install required packages
RUN apt-get update && apt-get install -y \
    ros-jazzy-foxglove-bridge \
    ros-jazzy-rosbag2

# set ros domain
ENV ROS_DOMAIN_ID=69

COPY docker/player/entrypoint.sh entrypoint.sh

# give executing rights to bash script
RUN chmod +x entrypoint.sh

# run script
ENTRYPOINT ["/entrypoint.sh"]
