version: "3.9"

services:
  ros-multisense:
    build:
      context: ../..
      dockerfile: docker/orin/Dockerfile.multisense
    container_name: ros-multisense
    network_mode: host
    restart: unless-stopped

  ros-recording:
    build:
      context: ../..
      dockerfile: docker/orin/Dockerfile.recorder
    container_name: ros-recorder
    network_mode: host
    volumes:
      - /mnt/Burak2/bags:/app/bags
    restart: unless-stopped
