# this file has multisense drivers, and other necessary packages
# for recording (rosbag) and inspecting (foxglove)
FROM ros:jazzy-ros-core

# setup working directory
WORKDIR /app

# install dependencies from apt
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    python3-colcon-common-extensions \
    python3-rosdep \
    ros-jazzy-rosbag2 

# set ros domain
ENV ROS_DOMAIN_ID=69

COPY launch/recorder_launch.py launch.py
COPY launch/recorder_params.yaml recorder_params.yaml

COPY docker/ros_entrypoint.sh entrypoint.sh
RUN chmod +x entrypoint.sh

STOPSIGNAL SIGINT

ENTRYPOINT ["./entrypoint.sh"]
CMD ["ros2", "launch", "launch.py"]
