# this file has multisense drivers, and other necessary packages
# for recording (rosbag) and inspecting (foxglove)
FROM ros:jazzy-ros-core

# setup working directory
WORKDIR /app

# copy multisense driver code
COPY src/multisense_stereo_camera src/multisense_stereo_camera

# install dependencies from apt
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    python3-colcon-common-extensions \
    python3-rosdep \

# make ros build
RUN . /opt/ros/jazzy/setup.sh && \
    rosdep init &&  \
    rosdep update && \
    rosdep install --from-paths src -y --ignore-src && \
    colcon build --symlink-install

# set ros domain
ENV ROS_DOMAIN_ID=69

# copy launch script last
COPY launch/multisense_launch.py launch.py

# launch ros package
CMD ["bash", "-c", "source install/setup.bash && ros2 launch launch.py"]
