services:
  ros-recording:
    build:
      context: ../..
      dockerfile: docker/orin/Dockerfile.recorder
    container_name: ros-recorder
    network_mode: host
    volumes:
      - /mnt/Burak2/ros-device-control/bags:/app/bags
    restart: unless-stopped
    stop_grace_period: 24h
